### ISSUE TITLE
Pollutant not being saved as part of scenario

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#39]
When a scenario is saved, C-LINE is exited, C-LINE is started, and the scenario is loaded, the pollutant is always NOx (the first pollutant in the drop-down box). 

Further, if the pollutant for a scenario is changed during a C-LINE session and a different scenario is then loaded, that scenario is displayed with the pollutant selected for the other scenario. For example, load a saved scenario, set the pollutant to Benzene, optionally save the scenario, load a different scenario, the pollutant in the Perform Analysis screen is displayed as Benzene.

**Comment by michellegrace** [comment]
I think this can be addressed in a future release. We may want to re-consider how we are doing the compare scenarios. Specifically, when the user chooses the type of calculation and the pollutant. Currently these are selected in both the perform analysis and the compare windows, this means that the user could make different choices at each point and the program will still run since concentrations are computed "on-the fly" for both scenarios selected in the compare window. Although, this may be slightly confusing at this point, the selections insure a consistent computation between scenarios when they are compared (i.e. the hourly/annual and pollutant are the same). 

So for now I think we can leave the type of computation and the pollutant out of the user options in a saved scenario.
