### ISSUE TITLE
Compare scenarios is still not correct

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#58]
I ran the same scenario as the Raleigh_Base in #47. This time I decreased the same segment of US1 south of Raleigh, saved and named this "Raleigh_decUS1".
![screen shot 2015-01-26 at 2 16 24 pm](https://cloud.githubusercontent.com/assets/10077162/5906568/a32e21ac-a566-11e4-8d85-54605f1272b4.png)

I got a relative difference like this (looks correct):
![screen shot 2015-01-26 at 2 21 54 pm](https://cloud.githubusercontent.com/assets/10077162/5906579/b6f1f056-a566-11e4-93fc-d74d8aabf1ff.png)

Then I calculated the % difference (looks incorrect):
![screen shot 2015-01-26 at 2 19 59 pm](https://cloud.githubusercontent.com/assets/10077162/5906583/c4b6a344-a566-11e4-8cb0-178cea88faa3.png)

There should be a negative %, cause the change in the road link should decrease the impact of the roadway.

For reference I ran the scenario where I increased US1 AADT as before. 

The relative difference looks correct:
![screen shot 2015-01-26 at 2 29 20 pm](https://cloud.githubusercontent.com/assets/10077162/5906727/ddf2d8b8-a567-11e4-8814-a2fc8a64d45b.png)

However, the % difference looks incorrect: 
![screen shot 2015-01-26 at 2 30 58 pm](https://cloud.githubusercontent.com/assets/10077162/5906741/f7f41196-a567-11e4-8296-814a0336297d.png)

These images should be very similar, because you are applying a scaling factor of 100/base.

**Comment by nathan-rice** [comment]
That percent difference plot looks correct to me.  The value range is locked to 0-100 based on Sarav's request to clip values to that range, because of the issue we had where a value divided by a very small value produced astronomically large values which basically washed out the rest of the plot.

**Comment by joellenb** [comment]
The range is incorrect. It needs to include negative percents and the change may be greater than 100.

Jo Ellen

**Comment by nathan-rice** [comment]
I am already aware that the value could be greater than 100 or less than 0.  Sarav specifically requested the current behavior.  The reason is because when we had unclipped ranges, random points on the map that were extremely low in base and just low or moderate in new would cause the percentage value reported to be astronomically high.  This would cause the rest of the results to be "washed out" because they were so small compared to the random super-high values.

I agree that having negative percentages (at least up to 100%) on the plot would be informative.  I defer to Sarav on how he would like this handled.

**Comment by joellenb** [comment]
Sarav,

Please reply to this. We are trying to take care of the issue of negative values not displaying on the Difference% plots.

If you want to eliminate small numbers, they should be in a range on both sides of 0 (e.g., -0.5 = +0.5 become 0.0) instead of eliminating all negative numbers. Also, the true percentage difference may be greater than 100 (i.e., double).

Thank you.

Jo Ellen

**Comment by joellenb** [comment]
I concur with showing a fixed range from –100% to +100% always, and then show cool colors (for decrease) and hot colors (for increases). This will also put a nice QA on our product, to confirm that we don’t see unexpected ranges.

See sample figures from a different software product, though the ranges go only from –50 to +50% in scale1.gif and -1 to +1% in scale3.gif. Another feature here is that small differences (+/– 0.5%) are all shown in white in scale1.gif.  We could use something like that here here too, so that we are focusing only on differences that matter.

Sarav

From: <Brandmeyer>, Jo Ellen <ellenjo@email.unc.edu<mailto:ellenjo@email.unc.edu>>
Date: Tuesday, January 27, 2015 at 10:03 AM
To: Sarav Arunachalam <sarav@email.unc.edu<mailto:sarav@email.unc.edu>>
Cc: nathan-rice/ctools <reply@reply.github.com<mailto:reply@reply.github.com>>, nathan-rice/ctools <ctools@noreply.github.com<mailto:ctools@noreply.github.com>>
Subject: RE: [ctools] Compare scenarios is still not correct (#58)

Sarav,

Please reply to this. We are trying to take care of the issue of negative values not displaying on the Difference% plots.

If you want to eliminate small numbers, they should be in a range on both sides of 0 (e.g., -0.5 = +0.5 become 0.0) instead of eliminating all negative numbers. Also, the true percentage difference may be greater than 100 (i.e., double).

Thank you.

Jo Ellen

**Comment by arunacs** [comment]
![aec mave-pdiff sens05a_nolnox 36k 01 scale3](https://cloud.githubusercontent.com/assets/10534766/5922253/045fb272-a618-11e4-843b-a1721da7377a.gif)
![aec mave-pdiff sens05a_nolnox 36k 07 scale1](https://cloud.githubusercontent.com/assets/10534766/5922252/045fbda8-a618-11e4-857e-b757c62dc4cd.gif)

**Comment by michellegrace** [comment]
I would also agree with this scaling. However, I am not a fan of the purple on the top of the "hot" side of the scale, I think it looks too similar to the blue.

**Comment by nathan-rice** [comment]
Updated the range of the plots.  Please create a separate issue for rendering 0 as transparent.
